# NUMPY

## Definition :
NumPy is a powerful numerical computing library in Python that provides support for large, 
multi-dimensional arrays and matrices,along with a collection of high-level mathematical functions to operate on these arrays. 

## Installation:
NumPy can be installed using the following pip command:

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


## Importing NumPy:

Once installed, you can import NumPy in your Python script or Jupyter notebook:

In [2]:
import numpy as np

## NumPy Arrays:

The core data structure in NumPy is the numpy.ndarray, commonly referred to as a NumPy array.
NumPy arrays can be created from Python lists or other iterable objects.

In [5]:
import numpy as np

# Creating a NumPy array from a Python list
my_list = [[1, 2, 3, 4, 5],[2,3,4,4,5]]
my_array = np.array(my_list)
print(my_array)


[[1 2 3 4 5]
 [2 3 4 4 5]]


## Array Attributes:

NumPy arrays have several important attributes, such as shape, dtype, and size.

In [6]:
print(my_array.shape)  # Returns the dimensions of the array
print(my_array.dtype)  # Returns the data type of the elements
print(my_array.size)   # Returns the total number of elements

(2, 5)
int32
10


## Array Operations:

NumPy provides a wide range of mathematical operations that can be performed on arrays.
Element-wise operations are the default behavior in NumPy.

In [7]:
# Element-wise addition
result_array = my_array + 10
print(result_array)

[[11 12 13 14 15]
 [12 13 14 14 15]]


## Array Indexing and Slicing:

NumPy arrays support advanced indexing and slicing operations.

In [13]:
# Indexing
print(my_array[1])   # Access the first element

# Slicing
a=[1,2,3,4]
my_arr=np.array(a)
print(my_arr[1:3])  # Access elements from index 1 to 3


[2 3 4 4 5]
[2 3]


## Multi-dimensional Arrays:

NumPy can handle multi-dimensional arrays, providing a convenient way to represent matrices and higher-dimensional data.

In [8]:
# Creating a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


## Universal Functions (ufunc):

NumPy provides universal functions that operate element-wise on arrays. These functions are highly optimized and can significantly improve performance.

In [14]:
# Example of a ufunc: Square root of each element
result = np.sqrt(my_array)
print(result)

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [1.41421356 1.73205081 2.         2.         2.23606798]]


## Linear Algebra Operations:

NumPy includes a variety of functions for linear algebra operations, such as matrix multiplication, determinant, and eigenvalues.

In [15]:
# Matrix multiplication
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
result_matrix = np.dot(matrix_a, matrix_b)
print(result)

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [1.41421356 1.73205081 2.         2.         2.23606798]]


## Random Module:

NumPy provides a random module for generating random numbers and distributions.

In [17]:
# Generating random numbers
random_array = np.random.rand(3, 3)  # 3x3 array with random values between 0 and 1
print(random_array)

[[0.86359412 0.72903199 0.0383724 ]
 [0.5255678  0.22211623 0.21780434]
 [0.09056055 0.74060736 0.41979831]]


In [3]:
array1=np.array([[2,3,4],[5,6,7],[8,9,0],[4,2,9]])
print(array1)

[[2 3 4]
 [5 6 7]
 [8 9 0]
 [4 2 9]]


In [5]:
print(array1[0,])

[2 3 4]


In [5]:
print(array1[:,1])

[3 6 9 2]


In [6]:
print(array1[1:3,1:3])

[[6 7]
 [9 0]]
